/* tslint:disable */
/* eslint-disable */
/**
 * @org/source
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Crystal sprites
 * @export
 * @interface Crystal
 */
export interface Crystal {
    /**
     * The default depiction of this Pokémon from the back in battle
     * @type {string}
     * @memberof Crystal
     */
    back_default: string | null;
    /**
     * The shiny depiction of this Pokémon from the back in battle
     * @type {string}
     * @memberof Crystal
     */
    back_shiny: string | null;
    /**
     * The back shiny transparent depiction of this Pokémon from the back in battle
     * @type {string}
     * @memberof Crystal
     */
    back_shiny_transparent: string | null;
    /**
     * The transparent depiction of this Pokémon from the back in battle
     * @type {string}
     * @memberof Crystal
     */
    back_transparent: string | null;
    /**
     * The default depiction of this Pokémon from the front in battle
     * @type {string}
     * @memberof Crystal
     */
    front_default: string | null;
    /**
     * The shiny depiction of this Pokémon from the front in battle
     * @type {string}
     * @memberof Crystal
     */
    front_shiny: string | null;
    /**
     * The front shiny transparent depiction of this Pokémon from the front in battle
     * @type {string}
     * @memberof Crystal
     */
    front_shiny_transparent: string | null;
    /**
     * The transparent depiction of this Pokémon from the front in battle
     * @type {string}
     * @memberof Crystal
     */
    front_transparent: string | null;
}

/**
 * Check if a given object implements the Crystal interface.
 */
export function instanceOfCrystal(value: object): value is Crystal {
    if (!('back_default' in value) || value['back_default'] === undefined) return false;
    if (!('back_shiny' in value) || value['back_shiny'] === undefined) return false;
    if (!('back_shiny_transparent' in value) || value['back_shiny_transparent'] === undefined) return false;
    if (!('back_transparent' in value) || value['back_transparent'] === undefined) return false;
    if (!('front_default' in value) || value['front_default'] === undefined) return false;
    if (!('front_shiny' in value) || value['front_shiny'] === undefined) return false;
    if (!('front_shiny_transparent' in value) || value['front_shiny_transparent'] === undefined) return false;
    if (!('front_transparent' in value) || value['front_transparent'] === undefined) return false;
    return true;
}

export function CrystalFromJSON(json: any): Crystal {
    return CrystalFromJSONTyped(json, false);
}

export function CrystalFromJSONTyped(json: any, ignoreDiscriminator: boolean): Crystal {
    if (json == null) {
        return json;
    }
    return {
        
        'back_default': json['back_default'],
        'back_shiny': json['back_shiny'],
        'back_shiny_transparent': json['back_shiny_transparent'],
        'back_transparent': json['back_transparent'],
        'front_default': json['front_default'],
        'front_shiny': json['front_shiny'],
        'front_shiny_transparent': json['front_shiny_transparent'],
        'front_transparent': json['front_transparent'],
    };
}

export function CrystalToJSON(json: any): Crystal {
    return CrystalToJSONTyped(json, false);
}

export function CrystalToJSONTyped(value?: Crystal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'back_default': value['back_default'],
        'back_shiny': value['back_shiny'],
        'back_shiny_transparent': value['back_shiny_transparent'],
        'back_transparent': value['back_transparent'],
        'front_default': value['front_default'],
        'front_shiny': value['front_shiny'],
        'front_shiny_transparent': value['front_shiny_transparent'],
        'front_transparent': value['front_transparent'],
    };
}

