/* tslint:disable */
/* eslint-disable */
/**
 * @org/source
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Dream World sprites
 * @export
 * @interface DreamWorld
 */
export interface DreamWorld {
    /**
     * The default depiction of this Pokémon from the front in battle
     * @type {string}
     * @memberof DreamWorld
     */
    front_default: string | null;
    /**
     * The female depiction of this Pokémon from the front in battle
     * @type {string}
     * @memberof DreamWorld
     */
    front_female: string | null;
}

/**
 * Check if a given object implements the DreamWorld interface.
 */
export function instanceOfDreamWorld(value: object): value is DreamWorld {
    if (!('front_default' in value) || value['front_default'] === undefined) return false;
    if (!('front_female' in value) || value['front_female'] === undefined) return false;
    return true;
}

export function DreamWorldFromJSON(json: any): DreamWorld {
    return DreamWorldFromJSONTyped(json, false);
}

export function DreamWorldFromJSONTyped(json: any, ignoreDiscriminator: boolean): DreamWorld {
    if (json == null) {
        return json;
    }
    return {
        
        'front_default': json['front_default'],
        'front_female': json['front_female'],
    };
}

export function DreamWorldToJSON(json: any): DreamWorld {
    return DreamWorldToJSONTyped(json, false);
}

export function DreamWorldToJSONTyped(value?: DreamWorld | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'front_default': value['front_default'],
        'front_female': value['front_female'],
    };
}

