/* tslint:disable */
/* eslint-disable */
/**
 * @org/source
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Emerald sprites
 * @export
 * @interface Emerald
 */
export interface Emerald {
    /**
     * The default depiction of this Pokémon from the front in battle
     * @type {string}
     * @memberof Emerald
     */
    front_default: string | null;
    /**
     * The shiny depiction of this Pokémon from the front in battle
     * @type {string}
     * @memberof Emerald
     */
    front_shiny: string | null;
}

/**
 * Check if a given object implements the Emerald interface.
 */
export function instanceOfEmerald(value: object): value is Emerald {
    if (!('front_default' in value) || value['front_default'] === undefined) return false;
    if (!('front_shiny' in value) || value['front_shiny'] === undefined) return false;
    return true;
}

export function EmeraldFromJSON(json: any): Emerald {
    return EmeraldFromJSONTyped(json, false);
}

export function EmeraldFromJSONTyped(json: any, ignoreDiscriminator: boolean): Emerald {
    if (json == null) {
        return json;
    }
    return {
        
        'front_default': json['front_default'],
        'front_shiny': json['front_shiny'],
    };
}

export function EmeraldToJSON(json: any): Emerald {
    return EmeraldToJSONTyped(json, false);
}

export function EmeraldToJSONTyped(value?: Emerald | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'front_default': value['front_default'],
        'front_shiny': value['front_shiny'],
    };
}

