/* tslint:disable */
/* eslint-disable */
/**
 * @org/source
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * FireRead LeafGreen sprites
 * @export
 * @interface FireredLeafgreen
 */
export interface FireredLeafgreen {
    /**
     * The default depiction of this Pokémon from the back in battle
     * @type {string}
     * @memberof FireredLeafgreen
     */
    back_default: string | null;
    /**
     * The shiny depiction of this Pokémon from the back in battle
     * @type {string}
     * @memberof FireredLeafgreen
     */
    back_shiny: string | null;
    /**
     * The default depiction of this Pokémon from the front in battle
     * @type {string}
     * @memberof FireredLeafgreen
     */
    front_default: string | null;
    /**
     * The shiny depiction of this Pokémon from the front in battle
     * @type {string}
     * @memberof FireredLeafgreen
     */
    front_shiny: string | null;
}

/**
 * Check if a given object implements the FireredLeafgreen interface.
 */
export function instanceOfFireredLeafgreen(value: object): value is FireredLeafgreen {
    if (!('back_default' in value) || value['back_default'] === undefined) return false;
    if (!('back_shiny' in value) || value['back_shiny'] === undefined) return false;
    if (!('front_default' in value) || value['front_default'] === undefined) return false;
    if (!('front_shiny' in value) || value['front_shiny'] === undefined) return false;
    return true;
}

export function FireredLeafgreenFromJSON(json: any): FireredLeafgreen {
    return FireredLeafgreenFromJSONTyped(json, false);
}

export function FireredLeafgreenFromJSONTyped(json: any, ignoreDiscriminator: boolean): FireredLeafgreen {
    if (json == null) {
        return json;
    }
    return {
        
        'back_default': json['back_default'],
        'back_shiny': json['back_shiny'],
        'front_default': json['front_default'],
        'front_shiny': json['front_shiny'],
    };
}

export function FireredLeafgreenToJSON(json: any): FireredLeafgreen {
    return FireredLeafgreenToJSONTyped(json, false);
}

export function FireredLeafgreenToJSONTyped(value?: FireredLeafgreen | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'back_default': value['back_default'],
        'back_shiny': value['back_shiny'],
        'front_default': value['front_default'],
        'front_shiny': value['front_shiny'],
    };
}

