/* tslint:disable */
/* eslint-disable */
/**
 * @org/source
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Platinum } from './Platinum';
import {
    PlatinumFromJSON,
    PlatinumFromJSONTyped,
    PlatinumToJSON,
    PlatinumToJSONTyped,
} from './Platinum';
import type { DiamondPearl } from './DiamondPearl';
import {
    DiamondPearlFromJSON,
    DiamondPearlFromJSONTyped,
    DiamondPearlToJSON,
    DiamondPearlToJSONTyped,
} from './DiamondPearl';
import type { HeartgoldSoulsilver } from './HeartgoldSoulsilver';
import {
    HeartgoldSoulsilverFromJSON,
    HeartgoldSoulsilverFromJSONTyped,
    HeartgoldSoulsilverToJSON,
    HeartgoldSoulsilverToJSONTyped,
} from './HeartgoldSoulsilver';

/**
 * Generation-IV Sprites
 * @export
 * @interface GenerationIVSprites
 */
export interface GenerationIVSprites {
    /**
     * 
     * @type {DiamondPearl}
     * @memberof GenerationIVSprites
     */
    diamond_pearl: DiamondPearl;
    /**
     * 
     * @type {HeartgoldSoulsilver}
     * @memberof GenerationIVSprites
     */
    heartgold_soulsilver: HeartgoldSoulsilver;
    /**
     * 
     * @type {Platinum}
     * @memberof GenerationIVSprites
     */
    platinum: Platinum;
}

/**
 * Check if a given object implements the GenerationIVSprites interface.
 */
export function instanceOfGenerationIVSprites(value: object): value is GenerationIVSprites {
    if (!('diamond_pearl' in value) || value['diamond_pearl'] === undefined) return false;
    if (!('heartgold_soulsilver' in value) || value['heartgold_soulsilver'] === undefined) return false;
    if (!('platinum' in value) || value['platinum'] === undefined) return false;
    return true;
}

export function GenerationIVSpritesFromJSON(json: any): GenerationIVSprites {
    return GenerationIVSpritesFromJSONTyped(json, false);
}

export function GenerationIVSpritesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerationIVSprites {
    if (json == null) {
        return json;
    }
    return {
        
        'diamond_pearl': DiamondPearlFromJSON(json['diamond-pearl']),
        'heartgold_soulsilver': HeartgoldSoulsilverFromJSON(json['heartgold-soulsilver']),
        'platinum': PlatinumFromJSON(json['platinum']),
    };
}

export function GenerationIVSpritesToJSON(json: any): GenerationIVSprites {
    return GenerationIVSpritesToJSONTyped(json, false);
}

export function GenerationIVSpritesToJSONTyped(value?: GenerationIVSprites | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'diamond-pearl': DiamondPearlToJSON(value['diamond_pearl']),
        'heartgold-soulsilver': HeartgoldSoulsilverToJSON(value['heartgold_soulsilver']),
        'platinum': PlatinumToJSON(value['platinum']),
    };
}

