/* tslint:disable */
/* eslint-disable */
/**
 * @org/source
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Generation VIII icons
 * @export
 * @interface GenerationViiiIcons
 */
export interface GenerationViiiIcons {
    /**
     * The default depiction of this Pokémon from the front in battle
     * @type {string}
     * @memberof GenerationViiiIcons
     */
    front_default: string | null;
    /**
     * The female depiction of this Pokémon from the front in battle
     * @type {string}
     * @memberof GenerationViiiIcons
     */
    front_female: string | null;
}

/**
 * Check if a given object implements the GenerationViiiIcons interface.
 */
export function instanceOfGenerationViiiIcons(value: object): value is GenerationViiiIcons {
    if (!('front_default' in value) || value['front_default'] === undefined) return false;
    if (!('front_female' in value) || value['front_female'] === undefined) return false;
    return true;
}

export function GenerationViiiIconsFromJSON(json: any): GenerationViiiIcons {
    return GenerationViiiIconsFromJSONTyped(json, false);
}

export function GenerationViiiIconsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerationViiiIcons {
    if (json == null) {
        return json;
    }
    return {
        
        'front_default': json['front_default'],
        'front_female': json['front_female'],
    };
}

export function GenerationViiiIconsToJSON(json: any): GenerationViiiIcons {
    return GenerationViiiIconsToJSONTyped(json, false);
}

export function GenerationViiiIconsToJSONTyped(value?: GenerationViiiIcons | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'front_default': value['front_default'],
        'front_female': value['front_female'],
    };
}

