/* tslint:disable */
/* eslint-disable */
/**
 * @org/source
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Emerald } from './Emerald';
import {
    EmeraldFromJSON,
    EmeraldFromJSONTyped,
    EmeraldToJSON,
    EmeraldToJSONTyped,
} from './Emerald';
import type { RubySapphire } from './RubySapphire';
import {
    RubySapphireFromJSON,
    RubySapphireFromJSONTyped,
    RubySapphireToJSON,
    RubySapphireToJSONTyped,
} from './RubySapphire';
import type { FireredLeafgreen } from './FireredLeafgreen';
import {
    FireredLeafgreenFromJSON,
    FireredLeafgreenFromJSONTyped,
    FireredLeafgreenToJSON,
    FireredLeafgreenToJSONTyped,
} from './FireredLeafgreen';

/**
 * Generation-III Sprites
 * @export
 * @interface GenerationIIISprites
 */
export interface GenerationIIISprites {
    /**
     * 
     * @type {Emerald}
     * @memberof GenerationIIISprites
     */
    emerald: Emerald;
    /**
     * 
     * @type {FireredLeafgreen}
     * @memberof GenerationIIISprites
     */
    firered_leafgreen: FireredLeafgreen;
    /**
     * 
     * @type {RubySapphire}
     * @memberof GenerationIIISprites
     */
    ruby_sapphire: RubySapphire;
}

/**
 * Check if a given object implements the GenerationIIISprites interface.
 */
export function instanceOfGenerationIIISprites(value: object): value is GenerationIIISprites {
    if (!('emerald' in value) || value['emerald'] === undefined) return false;
    if (!('firered_leafgreen' in value) || value['firered_leafgreen'] === undefined) return false;
    if (!('ruby_sapphire' in value) || value['ruby_sapphire'] === undefined) return false;
    return true;
}

export function GenerationIIISpritesFromJSON(json: any): GenerationIIISprites {
    return GenerationIIISpritesFromJSONTyped(json, false);
}

export function GenerationIIISpritesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerationIIISprites {
    if (json == null) {
        return json;
    }
    return {
        
        'emerald': EmeraldFromJSON(json['emerald']),
        'firered_leafgreen': FireredLeafgreenFromJSON(json['firered-leafgreen']),
        'ruby_sapphire': RubySapphireFromJSON(json['ruby-sapphire']),
    };
}

export function GenerationIIISpritesToJSON(json: any): GenerationIIISprites {
    return GenerationIIISpritesToJSONTyped(json, false);
}

export function GenerationIIISpritesToJSONTyped(value?: GenerationIIISprites | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'emerald': EmeraldToJSON(value['emerald']),
        'firered-leafgreen': FireredLeafgreenToJSON(value['firered_leafgreen']),
        'ruby-sapphire': RubySapphireToJSON(value['ruby_sapphire']),
    };
}

