/* tslint:disable */
/* eslint-disable */
/**
 * @org/source
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { XY } from './XY';
import {
    XYFromJSON,
    XYFromJSONTyped,
    XYToJSON,
    XYToJSONTyped,
} from './XY';
import type { OmegarubyAlphasapphire } from './OmegarubyAlphasapphire';
import {
    OmegarubyAlphasapphireFromJSON,
    OmegarubyAlphasapphireFromJSONTyped,
    OmegarubyAlphasapphireToJSON,
    OmegarubyAlphasapphireToJSONTyped,
} from './OmegarubyAlphasapphire';

/**
 * Generation-VI Sprites
 * @export
 * @interface GenerationVISprites
 */
export interface GenerationVISprites {
    /**
     * 
     * @type {OmegarubyAlphasapphire}
     * @memberof GenerationVISprites
     */
    omegaruby_alphasapphire: OmegarubyAlphasapphire;
    /**
     * 
     * @type {XY}
     * @memberof GenerationVISprites
     */
    x_y: XY;
}

/**
 * Check if a given object implements the GenerationVISprites interface.
 */
export function instanceOfGenerationVISprites(value: object): value is GenerationVISprites {
    if (!('omegaruby_alphasapphire' in value) || value['omegaruby_alphasapphire'] === undefined) return false;
    if (!('x_y' in value) || value['x_y'] === undefined) return false;
    return true;
}

export function GenerationVISpritesFromJSON(json: any): GenerationVISprites {
    return GenerationVISpritesFromJSONTyped(json, false);
}

export function GenerationVISpritesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerationVISprites {
    if (json == null) {
        return json;
    }
    return {
        
        'omegaruby_alphasapphire': OmegarubyAlphasapphireFromJSON(json['omegaruby-alphasapphire']),
        'x_y': XYFromJSON(json['x-y']),
    };
}

export function GenerationVISpritesToJSON(json: any): GenerationVISprites {
    return GenerationVISpritesToJSONTyped(json, false);
}

export function GenerationVISpritesToJSONTyped(value?: GenerationVISprites | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'omegaruby-alphasapphire': OmegarubyAlphasapphireToJSON(value['omegaruby_alphasapphire']),
        'x-y': XYToJSON(value['x_y']),
    };
}

