/* tslint:disable */
/* eslint-disable */
/**
 * @org/source
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RedBlue } from './RedBlue';
import {
    RedBlueFromJSON,
    RedBlueFromJSONTyped,
    RedBlueToJSON,
    RedBlueToJSONTyped,
} from './RedBlue';
import type { Yellow } from './Yellow';
import {
    YellowFromJSON,
    YellowFromJSONTyped,
    YellowToJSON,
    YellowToJSONTyped,
} from './Yellow';

/**
 * Generation-I Srites
 * @export
 * @interface GenerationISprites
 */
export interface GenerationISprites {
    /**
     * 
     * @type {RedBlue}
     * @memberof GenerationISprites
     */
    red_blue: RedBlue;
    /**
     * 
     * @type {Yellow}
     * @memberof GenerationISprites
     */
    yellow: Yellow;
}

/**
 * Check if a given object implements the GenerationISprites interface.
 */
export function instanceOfGenerationISprites(value: object): value is GenerationISprites {
    if (!('red_blue' in value) || value['red_blue'] === undefined) return false;
    if (!('yellow' in value) || value['yellow'] === undefined) return false;
    return true;
}

export function GenerationISpritesFromJSON(json: any): GenerationISprites {
    return GenerationISpritesFromJSONTyped(json, false);
}

export function GenerationISpritesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerationISprites {
    if (json == null) {
        return json;
    }
    return {
        
        'red_blue': RedBlueFromJSON(json['red-blue']),
        'yellow': YellowFromJSON(json['yellow']),
    };
}

export function GenerationISpritesToJSON(json: any): GenerationISprites {
    return GenerationISpritesToJSONTyped(json, false);
}

export function GenerationISpritesToJSONTyped(value?: GenerationISprites | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'red-blue': RedBlueToJSON(value['red_blue']),
        'yellow': YellowToJSON(value['yellow']),
    };
}

