/* tslint:disable */
/* eslint-disable */
/**
 * @org/source
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Generation VII icons
 * @export
 * @interface GenerationViiIcons
 */
export interface GenerationViiIcons {
    /**
     * The default depiction of this Pokémon from the front in battle
     * @type {string}
     * @memberof GenerationViiIcons
     */
    front_default: string | null;
    /**
     * The female depiction of this Pokémon from the front in battle
     * @type {string}
     * @memberof GenerationViiIcons
     */
    front_female: string | null;
}

/**
 * Check if a given object implements the GenerationViiIcons interface.
 */
export function instanceOfGenerationViiIcons(value: object): value is GenerationViiIcons {
    if (!('front_default' in value) || value['front_default'] === undefined) return false;
    if (!('front_female' in value) || value['front_female'] === undefined) return false;
    return true;
}

export function GenerationViiIconsFromJSON(json: any): GenerationViiIcons {
    return GenerationViiIconsFromJSONTyped(json, false);
}

export function GenerationViiIconsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerationViiIcons {
    if (json == null) {
        return json;
    }
    return {
        
        'front_default': json['front_default'],
        'front_female': json['front_female'],
    };
}

export function GenerationViiIconsToJSON(json: any): GenerationViiIcons {
    return GenerationViiIconsToJSONTyped(json, false);
}

export function GenerationViiIconsToJSONTyped(value?: GenerationViiIcons | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'front_default': value['front_default'],
        'front_female': value['front_female'],
    };
}

