/* tslint:disable */
/* eslint-disable */
/**
 * @org/source
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BlackWhite } from './BlackWhite';
import {
    BlackWhiteFromJSON,
    BlackWhiteFromJSONTyped,
    BlackWhiteToJSON,
    BlackWhiteToJSONTyped,
} from './BlackWhite';

/**
 * Generation-V Sprites
 * @export
 * @interface GenerationVSprites
 */
export interface GenerationVSprites {
    /**
     * 
     * @type {BlackWhite}
     * @memberof GenerationVSprites
     */
    black_white: BlackWhite;
}

/**
 * Check if a given object implements the GenerationVSprites interface.
 */
export function instanceOfGenerationVSprites(value: object): value is GenerationVSprites {
    if (!('black_white' in value) || value['black_white'] === undefined) return false;
    return true;
}

export function GenerationVSpritesFromJSON(json: any): GenerationVSprites {
    return GenerationVSpritesFromJSONTyped(json, false);
}

export function GenerationVSpritesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerationVSprites {
    if (json == null) {
        return json;
    }
    return {
        
        'black_white': BlackWhiteFromJSON(json['black-white']),
    };
}

export function GenerationVSpritesToJSON(json: any): GenerationVSprites {
    return GenerationVSpritesToJSONTyped(json, false);
}

export function GenerationVSpritesToJSONTyped(value?: GenerationVSprites | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'black-white': BlackWhiteToJSON(value['black_white']),
    };
}

