/* tslint:disable */
/* eslint-disable */
/**
 * @org/source
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Gold
 */
export interface Gold {
    /**
     * The default depiction of this Pokémon from the back in battle
     * @type {string}
     * @memberof Gold
     */
    back_default: string | null;
    /**
     * The shiny depiction of this Pokémon from the back in battle
     * @type {string}
     * @memberof Gold
     */
    back_shiny: string | null;
    /**
     * The default depiction of this Pokémon from the front in battle
     * @type {string}
     * @memberof Gold
     */
    front_default: string | null;
    /**
     * The shiny depiction of this Pokémon from the front in battle
     * @type {string}
     * @memberof Gold
     */
    front_shiny: string | null;
    /**
     * The transparent depiction of this Pokémon from the front in battle
     * @type {string}
     * @memberof Gold
     */
    front_transparent: string | null;
}

/**
 * Check if a given object implements the Gold interface.
 */
export function instanceOfGold(value: object): value is Gold {
    if (!('back_default' in value) || value['back_default'] === undefined) return false;
    if (!('back_shiny' in value) || value['back_shiny'] === undefined) return false;
    if (!('front_default' in value) || value['front_default'] === undefined) return false;
    if (!('front_shiny' in value) || value['front_shiny'] === undefined) return false;
    if (!('front_transparent' in value) || value['front_transparent'] === undefined) return false;
    return true;
}

export function GoldFromJSON(json: any): Gold {
    return GoldFromJSONTyped(json, false);
}

export function GoldFromJSONTyped(json: any, ignoreDiscriminator: boolean): Gold {
    if (json == null) {
        return json;
    }
    return {
        
        'back_default': json['back_default'],
        'back_shiny': json['back_shiny'],
        'front_default': json['front_default'],
        'front_shiny': json['front_shiny'],
        'front_transparent': json['front_transparent'],
    };
}

export function GoldToJSON(json: any): Gold {
    return GoldToJSONTyped(json, false);
}

export function GoldToJSONTyped(value?: Gold | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'back_default': value['back_default'],
        'back_shiny': value['back_shiny'],
        'front_default': value['front_default'],
        'front_shiny': value['front_shiny'],
        'front_transparent': value['front_transparent'],
    };
}

