/* tslint:disable */
/* eslint-disable */
/**
 * @org/source
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Home sprites
 * @export
 * @interface Home
 */
export interface Home {
    /**
     * The default depiction of this Pokémon from the front in battle
     * @type {string}
     * @memberof Home
     */
    front_default: string | null;
    /**
     * The female depiction of this Pokémon from the front in battle
     * @type {string}
     * @memberof Home
     */
    front_female: string | null;
    /**
     * The shiny depiction of this Pokémon from the front in battle
     * @type {string}
     * @memberof Home
     */
    front_shiny: string | null;
    /**
     * The shiny female depiction of this Pokémon from the back in battle
     * @type {string}
     * @memberof Home
     */
    front_shiny_female: string | null;
}

/**
 * Check if a given object implements the Home interface.
 */
export function instanceOfHome(value: object): value is Home {
    if (!('front_default' in value) || value['front_default'] === undefined) return false;
    if (!('front_female' in value) || value['front_female'] === undefined) return false;
    if (!('front_shiny' in value) || value['front_shiny'] === undefined) return false;
    if (!('front_shiny_female' in value) || value['front_shiny_female'] === undefined) return false;
    return true;
}

export function HomeFromJSON(json: any): Home {
    return HomeFromJSONTyped(json, false);
}

export function HomeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Home {
    if (json == null) {
        return json;
    }
    return {
        
        'front_default': json['front_default'],
        'front_female': json['front_female'],
        'front_shiny': json['front_shiny'],
        'front_shiny_female': json['front_shiny_female'],
    };
}

export function HomeToJSON(json: any): Home {
    return HomeToJSONTyped(json, false);
}

export function HomeToJSONTyped(value?: Home | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'front_default': value['front_default'],
        'front_female': value['front_female'],
        'front_shiny': value['front_shiny'],
        'front_shiny_female': value['front_shiny_female'],
    };
}

