/* tslint:disable */
/* eslint-disable */
/**
 * @org/source
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NamedAPIResource } from './NamedAPIResource';
import {
    NamedAPIResourceFromJSON,
    NamedAPIResourceFromJSONTyped,
    NamedAPIResourceToJSON,
    NamedAPIResourceToJSONTyped,
} from './NamedAPIResource';

/**
 * Calling any API endpoint without a resource ID or name will return a paginated list of available resources for that API.
 * By default, a list "page" will contain up to 20 resources. If you would like to change this just add a 'limit' query parameter
 * to the GET request, e.g. ?=60. You can use 'offset' to move to the next page, e.g. ?limit=60&offset=60
 * @export
 * @interface NamedAPIResourceList
 */
export interface NamedAPIResourceList {
    /**
     * The total number of resources available from this API
     * @type {number}
     * @memberof NamedAPIResourceList
     */
    count: number;
    /**
     * The URL for the next page in the list
     * @type {string}
     * @memberof NamedAPIResourceList
     */
    next: string | null;
    /**
     * The URL for the previous page in the list
     * @type {string}
     * @memberof NamedAPIResourceList
     */
    previous: string | null;
    /**
     * A list of named API resources
     * @type {Array<NamedAPIResource>}
     * @memberof NamedAPIResourceList
     */
    results: Array<NamedAPIResource>;
}

/**
 * Check if a given object implements the NamedAPIResourceList interface.
 */
export function instanceOfNamedAPIResourceList(value: object): value is NamedAPIResourceList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('next' in value) || value['next'] === undefined) return false;
    if (!('previous' in value) || value['previous'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function NamedAPIResourceListFromJSON(json: any): NamedAPIResourceList {
    return NamedAPIResourceListFromJSONTyped(json, false);
}

export function NamedAPIResourceListFromJSONTyped(json: any, ignoreDiscriminator: boolean): NamedAPIResourceList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'],
        'previous': json['previous'],
        'results': ((json['results'] as Array<any>).map(NamedAPIResourceFromJSON)),
    };
}

export function NamedAPIResourceListToJSON(json: any): NamedAPIResourceList {
    return NamedAPIResourceListToJSONTyped(json, false);
}

export function NamedAPIResourceListToJSONTyped(value?: NamedAPIResourceList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(NamedAPIResourceToJSON)),
    };
}

