/* tslint:disable */
/* eslint-disable */
/**
 * @org/source
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The name and the URL of the referenced resource
 * @export
 * @interface NamedAPIResource
 */
export interface NamedAPIResource {
    /**
     * The name of the referenced resource
     * @type {string}
     * @memberof NamedAPIResource
     */
    name: string;
    /**
     * The URL of the referenced resource
     * @type {string}
     * @memberof NamedAPIResource
     */
    url: string;
}

/**
 * Check if a given object implements the NamedAPIResource interface.
 */
export function instanceOfNamedAPIResource(value: object): value is NamedAPIResource {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function NamedAPIResourceFromJSON(json: any): NamedAPIResource {
    return NamedAPIResourceFromJSONTyped(json, false);
}

export function NamedAPIResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): NamedAPIResource {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'url': json['url'],
    };
}

export function NamedAPIResourceToJSON(json: any): NamedAPIResource {
    return NamedAPIResourceToJSONTyped(json, false);
}

export function NamedAPIResourceToJSONTyped(value?: NamedAPIResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'url': value['url'],
    };
}

