/* tslint:disable */
/* eslint-disable */
/**
 * @org/source
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Official Artwork sprites
 * @export
 * @interface OfficialArtwork
 */
export interface OfficialArtwork {
    /**
     * The default depiction of this Pokémon from the front in battle
     * @type {string}
     * @memberof OfficialArtwork
     */
    front_default: string | null;
}

/**
 * Check if a given object implements the OfficialArtwork interface.
 */
export function instanceOfOfficialArtwork(value: object): value is OfficialArtwork {
    if (!('front_default' in value) || value['front_default'] === undefined) return false;
    return true;
}

export function OfficialArtworkFromJSON(json: any): OfficialArtwork {
    return OfficialArtworkFromJSONTyped(json, false);
}

export function OfficialArtworkFromJSONTyped(json: any, ignoreDiscriminator: boolean): OfficialArtwork {
    if (json == null) {
        return json;
    }
    return {
        
        'front_default': json['front_default'],
    };
}

export function OfficialArtworkToJSON(json: any): OfficialArtwork {
    return OfficialArtworkToJSONTyped(json, false);
}

export function OfficialArtworkToJSONTyped(value?: OfficialArtwork | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'front_default': value['front_default'],
    };
}

