/* tslint:disable */
/* eslint-disable */
/**
 * @org/source
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DreamWorld } from './DreamWorld';
import {
    DreamWorldFromJSON,
    DreamWorldFromJSONTyped,
    DreamWorldToJSON,
    DreamWorldToJSONTyped,
} from './DreamWorld';
import type { OfficialArtwork } from './OfficialArtwork';
import {
    OfficialArtworkFromJSON,
    OfficialArtworkFromJSONTyped,
    OfficialArtworkToJSON,
    OfficialArtworkToJSONTyped,
} from './OfficialArtwork';
import type { Home } from './Home';
import {
    HomeFromJSON,
    HomeFromJSONTyped,
    HomeToJSON,
    HomeToJSONTyped,
} from './Home';

/**
 * Other Pokemon Sprites (Dream World and Official Artwork sprites)
 * @export
 * @interface OtherPokemonSprites
 */
export interface OtherPokemonSprites {
    /**
     * 
     * @type {DreamWorld}
     * @memberof OtherPokemonSprites
     */
    dream_world: DreamWorld;
    /**
     * 
     * @type {OfficialArtwork}
     * @memberof OtherPokemonSprites
     */
    official_artwork: OfficialArtwork;
    /**
     * 
     * @type {Home}
     * @memberof OtherPokemonSprites
     */
    home: Home;
}

/**
 * Check if a given object implements the OtherPokemonSprites interface.
 */
export function instanceOfOtherPokemonSprites(value: object): value is OtherPokemonSprites {
    if (!('dream_world' in value) || value['dream_world'] === undefined) return false;
    if (!('official_artwork' in value) || value['official_artwork'] === undefined) return false;
    if (!('home' in value) || value['home'] === undefined) return false;
    return true;
}

export function OtherPokemonSpritesFromJSON(json: any): OtherPokemonSprites {
    return OtherPokemonSpritesFromJSONTyped(json, false);
}

export function OtherPokemonSpritesFromJSONTyped(json: any, ignoreDiscriminator: boolean): OtherPokemonSprites {
    if (json == null) {
        return json;
    }
    return {
        
        'dream_world': DreamWorldFromJSON(json['dream_world']),
        'official_artwork': OfficialArtworkFromJSON(json['official-artwork']),
        'home': HomeFromJSON(json['home']),
    };
}

export function OtherPokemonSpritesToJSON(json: any): OtherPokemonSprites {
    return OtherPokemonSpritesToJSONTyped(json, false);
}

export function OtherPokemonSpritesToJSONTyped(value?: OtherPokemonSprites | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dream_world': DreamWorldToJSON(value['dream_world']),
        'official-artwork': OfficialArtworkToJSON(value['official_artwork']),
        'home': HomeToJSON(value['home']),
    };
}

