/* tslint:disable */
/* eslint-disable */
/**
 * @org/source
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Platinum
 */
export interface Platinum {
    /**
     * The default depiction of this Pokémon from the back in battle
     * @type {string}
     * @memberof Platinum
     */
    back_default: string | null;
    /**
     * The shiny depiction of this Pokémon from the back in battle
     * @type {string}
     * @memberof Platinum
     */
    back_shiny: string | null;
    /**
     * The female depiction of this Pokémon from the back in battle
     * @type {string}
     * @memberof Platinum
     */
    back_female: string | null;
    /**
     * The default depiction of this Pokémon from the front in battle
     * @type {string}
     * @memberof Platinum
     */
    front_default: string | null;
    /**
     * The shiny depiction of this Pokémon from the front in battle
     * @type {string}
     * @memberof Platinum
     */
    front_shiny: string | null;
    /**
     * The shiny female depiction of this Pokémon from the back in battle
     * @type {string}
     * @memberof Platinum
     */
    back_shiny_female: string | null;
    /**
     * The female depiction of this Pokémon from the front in battle
     * @type {string}
     * @memberof Platinum
     */
    front_female: string | null;
    /**
     * The shiny female depiction of this Pokémon from the back in battle
     * @type {string}
     * @memberof Platinum
     */
    front_shiny_female: string | null;
}

/**
 * Check if a given object implements the Platinum interface.
 */
export function instanceOfPlatinum(value: object): value is Platinum {
    if (!('back_default' in value) || value['back_default'] === undefined) return false;
    if (!('back_shiny' in value) || value['back_shiny'] === undefined) return false;
    if (!('back_female' in value) || value['back_female'] === undefined) return false;
    if (!('front_default' in value) || value['front_default'] === undefined) return false;
    if (!('front_shiny' in value) || value['front_shiny'] === undefined) return false;
    if (!('back_shiny_female' in value) || value['back_shiny_female'] === undefined) return false;
    if (!('front_female' in value) || value['front_female'] === undefined) return false;
    if (!('front_shiny_female' in value) || value['front_shiny_female'] === undefined) return false;
    return true;
}

export function PlatinumFromJSON(json: any): Platinum {
    return PlatinumFromJSONTyped(json, false);
}

export function PlatinumFromJSONTyped(json: any, ignoreDiscriminator: boolean): Platinum {
    if (json == null) {
        return json;
    }
    return {
        
        'back_default': json['back_default'],
        'back_shiny': json['back_shiny'],
        'back_female': json['back_female'],
        'front_default': json['front_default'],
        'front_shiny': json['front_shiny'],
        'back_shiny_female': json['back_shiny_female'],
        'front_female': json['front_female'],
        'front_shiny_female': json['front_shiny_female'],
    };
}

export function PlatinumToJSON(json: any): Platinum {
    return PlatinumToJSONTyped(json, false);
}

export function PlatinumToJSONTyped(value?: Platinum | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'back_default': value['back_default'],
        'back_shiny': value['back_shiny'],
        'back_female': value['back_female'],
        'front_default': value['front_default'],
        'front_shiny': value['front_shiny'],
        'back_shiny_female': value['back_shiny_female'],
        'front_female': value['front_female'],
        'front_shiny_female': value['front_shiny_female'],
    };
}

