/* tslint:disable */
/* eslint-disable */
/**
 * @org/source
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NamedAPIResource } from './NamedAPIResource';
import {
    NamedAPIResourceFromJSON,
    NamedAPIResourceFromJSONTyped,
    NamedAPIResourceToJSON,
    NamedAPIResourceToJSONTyped,
} from './NamedAPIResource';

/**
 * The details of the version in which the Pokémon can learn the move
 * @export
 * @interface PokemonMoveVersion
 */
export interface PokemonMoveVersion {
    /**
     * 
     * @type {NamedAPIResource}
     * @memberof PokemonMoveVersion
     */
    move_learn_method: NamedAPIResource;
    /**
     * 
     * @type {NamedAPIResource}
     * @memberof PokemonMoveVersion
     */
    version_group: NamedAPIResource;
    /**
     * The minimum level to learn the move
     * @type {number}
     * @memberof PokemonMoveVersion
     */
    level_learned_at: number;
}

/**
 * Check if a given object implements the PokemonMoveVersion interface.
 */
export function instanceOfPokemonMoveVersion(value: object): value is PokemonMoveVersion {
    if (!('move_learn_method' in value) || value['move_learn_method'] === undefined) return false;
    if (!('version_group' in value) || value['version_group'] === undefined) return false;
    if (!('level_learned_at' in value) || value['level_learned_at'] === undefined) return false;
    return true;
}

export function PokemonMoveVersionFromJSON(json: any): PokemonMoveVersion {
    return PokemonMoveVersionFromJSONTyped(json, false);
}

export function PokemonMoveVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PokemonMoveVersion {
    if (json == null) {
        return json;
    }
    return {
        
        'move_learn_method': NamedAPIResourceFromJSON(json['move_learn_method']),
        'version_group': NamedAPIResourceFromJSON(json['version_group']),
        'level_learned_at': json['level_learned_at'],
    };
}

export function PokemonMoveVersionToJSON(json: any): PokemonMoveVersion {
    return PokemonMoveVersionToJSONTyped(json, false);
}

export function PokemonMoveVersionToJSONTyped(value?: PokemonMoveVersion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'move_learn_method': NamedAPIResourceToJSON(value['move_learn_method']),
        'version_group': NamedAPIResourceToJSON(value['version_group']),
        'level_learned_at': value['level_learned_at'],
    };
}

