/* tslint:disable */
/* eslint-disable */
/**
 * @org/source
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PokemonDetailsSprites
 */
export interface PokemonDetailsSprites {
    /**
     * 
     * @type {string}
     * @memberof PokemonDetailsSprites
     */
    back_default: string | null;
    /**
     * 
     * @type {string}
     * @memberof PokemonDetailsSprites
     */
    front_default: string | null;
}

/**
 * Check if a given object implements the PokemonDetailsSprites interface.
 */
export function instanceOfPokemonDetailsSprites(value: object): value is PokemonDetailsSprites {
    if (!('back_default' in value) || value['back_default'] === undefined) return false;
    if (!('front_default' in value) || value['front_default'] === undefined) return false;
    return true;
}

export function PokemonDetailsSpritesFromJSON(json: any): PokemonDetailsSprites {
    return PokemonDetailsSpritesFromJSONTyped(json, false);
}

export function PokemonDetailsSpritesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PokemonDetailsSprites {
    if (json == null) {
        return json;
    }
    return {
        
        'back_default': json['back_default'],
        'front_default': json['front_default'],
    };
}

export function PokemonDetailsSpritesToJSON(json: any): PokemonDetailsSprites {
    return PokemonDetailsSpritesToJSONTyped(json, false);
}

export function PokemonDetailsSpritesToJSONTyped(value?: PokemonDetailsSprites | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'back_default': value['back_default'],
        'front_default': value['front_default'],
    };
}

