/* tslint:disable */
/* eslint-disable */
/**
 * @org/source
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NamedAPIResource } from './NamedAPIResource';
import {
    NamedAPIResourceFromJSON,
    NamedAPIResourceFromJSONTyped,
    NamedAPIResourceToJSON,
    NamedAPIResourceToJSONTyped,
} from './NamedAPIResource';

/**
 * Abilities the given pokémon could potentially have
 * @export
 * @interface PokemonAbility
 */
export interface PokemonAbility {
    /**
     * Whether or not this is a hidden ability
     * @type {boolean}
     * @memberof PokemonAbility
     */
    is_hidden: boolean;
    /**
     * The slot this ability occupies in this Pokémon species
     * @type {number}
     * @memberof PokemonAbility
     */
    slot: number;
    /**
     * 
     * @type {NamedAPIResource}
     * @memberof PokemonAbility
     */
    ability: NamedAPIResource;
}

/**
 * Check if a given object implements the PokemonAbility interface.
 */
export function instanceOfPokemonAbility(value: object): value is PokemonAbility {
    if (!('is_hidden' in value) || value['is_hidden'] === undefined) return false;
    if (!('slot' in value) || value['slot'] === undefined) return false;
    if (!('ability' in value) || value['ability'] === undefined) return false;
    return true;
}

export function PokemonAbilityFromJSON(json: any): PokemonAbility {
    return PokemonAbilityFromJSONTyped(json, false);
}

export function PokemonAbilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): PokemonAbility {
    if (json == null) {
        return json;
    }
    return {
        
        'is_hidden': json['is_hidden'],
        'slot': json['slot'],
        'ability': NamedAPIResourceFromJSON(json['ability']),
    };
}

export function PokemonAbilityToJSON(json: any): PokemonAbility {
    return PokemonAbilityToJSONTyped(json, false);
}

export function PokemonAbilityToJSONTyped(value?: PokemonAbility | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_hidden': value['is_hidden'],
        'slot': value['slot'],
        'ability': NamedAPIResourceToJSON(value['ability']),
    };
}

