/* tslint:disable */
/* eslint-disable */
/**
 * @org/source
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PokemonStat } from './PokemonStat';
import {
    PokemonStatFromJSON,
    PokemonStatFromJSONTyped,
    PokemonStatToJSON,
    PokemonStatToJSONTyped,
} from './PokemonStat';
import type { PokemonAbility } from './PokemonAbility';
import {
    PokemonAbilityFromJSON,
    PokemonAbilityFromJSONTyped,
    PokemonAbilityToJSON,
    PokemonAbilityToJSONTyped,
} from './PokemonAbility';
import type { PokemonDetailsSprites } from './PokemonDetailsSprites';
import {
    PokemonDetailsSpritesFromJSON,
    PokemonDetailsSpritesFromJSONTyped,
    PokemonDetailsSpritesToJSON,
    PokemonDetailsSpritesToJSONTyped,
} from './PokemonDetailsSprites';
import type { PokemonMovesByCategory } from './PokemonMovesByCategory';
import {
    PokemonMovesByCategoryFromJSON,
    PokemonMovesByCategoryFromJSONTyped,
    PokemonMovesByCategoryToJSON,
    PokemonMovesByCategoryToJSONTyped,
} from './PokemonMovesByCategory';
import type { PokemonType } from './PokemonType';
import {
    PokemonTypeFromJSON,
    PokemonTypeFromJSONTyped,
    PokemonTypeToJSON,
    PokemonTypeToJSONTyped,
} from './PokemonType';

/**
 * 
 * @export
 * @interface PokemonDetails
 */
export interface PokemonDetails {
    /**
     * 
     * @type {PokemonDetailsSprites}
     * @memberof PokemonDetails
     */
    sprites: PokemonDetailsSprites;
    /**
     * 
     * @type {PokemonMovesByCategory}
     * @memberof PokemonDetails
     */
    moves: PokemonMovesByCategory;
    /**
     * 
     * @type {Array<PokemonType>}
     * @memberof PokemonDetails
     */
    types: Array<PokemonType>;
    /**
     * 
     * @type {Array<PokemonStat>}
     * @memberof PokemonDetails
     */
    stats: Array<PokemonStat>;
    /**
     * 
     * @type {string}
     * @memberof PokemonDetails
     */
    name: string;
    /**
     * 
     * @type {Array<PokemonAbility>}
     * @memberof PokemonDetails
     */
    abilities: Array<PokemonAbility>;
    /**
     * 
     * @type {number}
     * @memberof PokemonDetails
     */
    id: number;
}

/**
 * Check if a given object implements the PokemonDetails interface.
 */
export function instanceOfPokemonDetails(value: object): value is PokemonDetails {
    if (!('sprites' in value) || value['sprites'] === undefined) return false;
    if (!('moves' in value) || value['moves'] === undefined) return false;
    if (!('types' in value) || value['types'] === undefined) return false;
    if (!('stats' in value) || value['stats'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('abilities' in value) || value['abilities'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function PokemonDetailsFromJSON(json: any): PokemonDetails {
    return PokemonDetailsFromJSONTyped(json, false);
}

export function PokemonDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PokemonDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'sprites': PokemonDetailsSpritesFromJSON(json['sprites']),
        'moves': PokemonMovesByCategoryFromJSON(json['moves']),
        'types': ((json['types'] as Array<any>).map(PokemonTypeFromJSON)),
        'stats': ((json['stats'] as Array<any>).map(PokemonStatFromJSON)),
        'name': json['name'],
        'abilities': ((json['abilities'] as Array<any>).map(PokemonAbilityFromJSON)),
        'id': json['id'],
    };
}

export function PokemonDetailsToJSON(json: any): PokemonDetails {
    return PokemonDetailsToJSONTyped(json, false);
}

export function PokemonDetailsToJSONTyped(value?: PokemonDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sprites': PokemonDetailsSpritesToJSON(value['sprites']),
        'moves': PokemonMovesByCategoryToJSON(value['moves']),
        'types': ((value['types'] as Array<any>).map(PokemonTypeToJSON)),
        'stats': ((value['stats'] as Array<any>).map(PokemonStatToJSON)),
        'name': value['name'],
        'abilities': ((value['abilities'] as Array<any>).map(PokemonAbilityToJSON)),
        'id': value['id'],
    };
}

