/* tslint:disable */
/* eslint-disable */
/**
 * @org/source
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NamedAPIResource } from './NamedAPIResource';
import {
    NamedAPIResourceFromJSON,
    NamedAPIResourceFromJSONTyped,
    NamedAPIResourceToJSON,
    NamedAPIResourceToJSONTyped,
} from './NamedAPIResource';
import type { PokemonMoveVersion } from './PokemonMoveVersion';
import {
    PokemonMoveVersionFromJSON,
    PokemonMoveVersionFromJSONTyped,
    PokemonMoveVersionToJSON,
    PokemonMoveVersionToJSONTyped,
} from './PokemonMoveVersion';

/**
 * A Move along with learn methods and level details pertaining to specific version groups
 * @export
 * @interface PokemonMove
 */
export interface PokemonMove {
    /**
     * 
     * @type {NamedAPIResource}
     * @memberof PokemonMove
     */
    move: NamedAPIResource;
    /**
     * The details of the version in which the Pokémon can learn the move
     * @type {Array<PokemonMoveVersion>}
     * @memberof PokemonMove
     */
    version_group_details: Array<PokemonMoveVersion>;
}

/**
 * Check if a given object implements the PokemonMove interface.
 */
export function instanceOfPokemonMove(value: object): value is PokemonMove {
    if (!('move' in value) || value['move'] === undefined) return false;
    if (!('version_group_details' in value) || value['version_group_details'] === undefined) return false;
    return true;
}

export function PokemonMoveFromJSON(json: any): PokemonMove {
    return PokemonMoveFromJSONTyped(json, false);
}

export function PokemonMoveFromJSONTyped(json: any, ignoreDiscriminator: boolean): PokemonMove {
    if (json == null) {
        return json;
    }
    return {
        
        'move': NamedAPIResourceFromJSON(json['move']),
        'version_group_details': ((json['version_group_details'] as Array<any>).map(PokemonMoveVersionFromJSON)),
    };
}

export function PokemonMoveToJSON(json: any): PokemonMove {
    return PokemonMoveToJSONTyped(json, false);
}

export function PokemonMoveToJSONTyped(value?: PokemonMove | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'move': NamedAPIResourceToJSON(value['move']),
        'version_group_details': ((value['version_group_details'] as Array<any>).map(PokemonMoveVersionToJSON)),
    };
}

