/* tslint:disable */
/* eslint-disable */
/**
 * @org/source
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PokemonHeldItemVersion } from './PokemonHeldItemVersion';
import {
    PokemonHeldItemVersionFromJSON,
    PokemonHeldItemVersionFromJSONTyped,
    PokemonHeldItemVersionToJSON,
    PokemonHeldItemVersionToJSONTyped,
} from './PokemonHeldItemVersion';
import type { NamedAPIResource } from './NamedAPIResource';
import {
    NamedAPIResourceFromJSON,
    NamedAPIResourceFromJSONTyped,
    NamedAPIResourceToJSON,
    NamedAPIResourceToJSONTyped,
} from './NamedAPIResource';

/**
 * Items the given Pokémon may be holding when encountered
 * @export
 * @interface PokemonHeldItem
 */
export interface PokemonHeldItem {
    /**
     * 
     * @type {NamedAPIResource}
     * @memberof PokemonHeldItem
     */
    item: NamedAPIResource;
    /**
     * The details of the different versions in which the item is held
     * @type {Array<PokemonHeldItemVersion>}
     * @memberof PokemonHeldItem
     */
    version_details: Array<PokemonHeldItemVersion>;
}

/**
 * Check if a given object implements the PokemonHeldItem interface.
 */
export function instanceOfPokemonHeldItem(value: object): value is PokemonHeldItem {
    if (!('item' in value) || value['item'] === undefined) return false;
    if (!('version_details' in value) || value['version_details'] === undefined) return false;
    return true;
}

export function PokemonHeldItemFromJSON(json: any): PokemonHeldItem {
    return PokemonHeldItemFromJSONTyped(json, false);
}

export function PokemonHeldItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): PokemonHeldItem {
    if (json == null) {
        return json;
    }
    return {
        
        'item': NamedAPIResourceFromJSON(json['item']),
        'version_details': ((json['version_details'] as Array<any>).map(PokemonHeldItemVersionFromJSON)),
    };
}

export function PokemonHeldItemToJSON(json: any): PokemonHeldItem {
    return PokemonHeldItemToJSONTyped(json, false);
}

export function PokemonHeldItemToJSONTyped(value?: PokemonHeldItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'item': NamedAPIResourceToJSON(value['item']),
        'version_details': ((value['version_details'] as Array<any>).map(PokemonHeldItemVersionToJSON)),
    };
}

