/* tslint:disable */
/* eslint-disable */
/**
 * @org/source
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PokemonMove } from './PokemonMove';
import {
    PokemonMoveFromJSON,
    PokemonMoveFromJSONTyped,
    PokemonMoveToJSON,
    PokemonMoveToJSONTyped,
} from './PokemonMove';

/**
 * 
 * @export
 * @interface PokemonMovesByCategory
 */
export interface PokemonMovesByCategory {
    /**
     * 
     * @type {Array<PokemonMove>}
     * @memberof PokemonMovesByCategory
     */
    tutor: Array<PokemonMove>;
    /**
     * 
     * @type {Array<PokemonMove>}
     * @memberof PokemonMovesByCategory
     */
    machine: Array<PokemonMove>;
    /**
     * 
     * @type {Array<PokemonMove>}
     * @memberof PokemonMovesByCategory
     */
    levelUp: Array<PokemonMove>;
    /**
     * 
     * @type {Array<PokemonMove>}
     * @memberof PokemonMovesByCategory
     */
    egg: Array<PokemonMove>;
}

/**
 * Check if a given object implements the PokemonMovesByCategory interface.
 */
export function instanceOfPokemonMovesByCategory(value: object): value is PokemonMovesByCategory {
    if (!('tutor' in value) || value['tutor'] === undefined) return false;
    if (!('machine' in value) || value['machine'] === undefined) return false;
    if (!('levelUp' in value) || value['levelUp'] === undefined) return false;
    if (!('egg' in value) || value['egg'] === undefined) return false;
    return true;
}

export function PokemonMovesByCategoryFromJSON(json: any): PokemonMovesByCategory {
    return PokemonMovesByCategoryFromJSONTyped(json, false);
}

export function PokemonMovesByCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PokemonMovesByCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'tutor': ((json['tutor'] as Array<any>).map(PokemonMoveFromJSON)),
        'machine': ((json['machine'] as Array<any>).map(PokemonMoveFromJSON)),
        'levelUp': ((json['levelUp'] as Array<any>).map(PokemonMoveFromJSON)),
        'egg': ((json['egg'] as Array<any>).map(PokemonMoveFromJSON)),
    };
}

export function PokemonMovesByCategoryToJSON(json: any): PokemonMovesByCategory {
    return PokemonMovesByCategoryToJSONTyped(json, false);
}

export function PokemonMovesByCategoryToJSONTyped(value?: PokemonMovesByCategory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tutor': ((value['tutor'] as Array<any>).map(PokemonMoveToJSON)),
        'machine': ((value['machine'] as Array<any>).map(PokemonMoveToJSON)),
        'levelUp': ((value['levelUp'] as Array<any>).map(PokemonMoveToJSON)),
        'egg': ((value['egg'] as Array<any>).map(PokemonMoveToJSON)),
    };
}

