/* tslint:disable */
/* eslint-disable */
/**
 * @org/source
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NamedAPIResource } from './NamedAPIResource';
import {
    NamedAPIResourceFromJSON,
    NamedAPIResourceFromJSONTyped,
    NamedAPIResourceToJSON,
    NamedAPIResourceToJSONTyped,
} from './NamedAPIResource';

/**
 * The details of the different versions in which the item is held
 * @export
 * @interface PokemonHeldItemVersion
 */
export interface PokemonHeldItemVersion {
    /**
     * 
     * @type {NamedAPIResource}
     * @memberof PokemonHeldItemVersion
     */
    version: NamedAPIResource;
    /**
     * How often the item is held
     * @type {number}
     * @memberof PokemonHeldItemVersion
     */
    rarity: number;
}

/**
 * Check if a given object implements the PokemonHeldItemVersion interface.
 */
export function instanceOfPokemonHeldItemVersion(value: object): value is PokemonHeldItemVersion {
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('rarity' in value) || value['rarity'] === undefined) return false;
    return true;
}

export function PokemonHeldItemVersionFromJSON(json: any): PokemonHeldItemVersion {
    return PokemonHeldItemVersionFromJSONTyped(json, false);
}

export function PokemonHeldItemVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PokemonHeldItemVersion {
    if (json == null) {
        return json;
    }
    return {
        
        'version': NamedAPIResourceFromJSON(json['version']),
        'rarity': json['rarity'],
    };
}

export function PokemonHeldItemVersionToJSON(json: any): PokemonHeldItemVersion {
    return PokemonHeldItemVersionToJSONTyped(json, false);
}

export function PokemonHeldItemVersionToJSONTyped(value?: PokemonHeldItemVersion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': NamedAPIResourceToJSON(value['version']),
        'rarity': value['rarity'],
    };
}

