/* tslint:disable */
/* eslint-disable */
/**
 * @org/source
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NamedAPIResource } from './NamedAPIResource';
import {
    NamedAPIResourceFromJSON,
    NamedAPIResourceFromJSONTyped,
    NamedAPIResourceToJSON,
    NamedAPIResourceToJSONTyped,
} from './NamedAPIResource';

/**
 * Details showing types the given Pokémon has
 * @export
 * @interface PokemonType
 */
export interface PokemonType {
    /**
     * The order the Pokémon's types are listed in
     * @type {number}
     * @memberof PokemonType
     */
    slot: number;
    /**
     * 
     * @type {NamedAPIResource}
     * @memberof PokemonType
     */
    type: NamedAPIResource;
}

/**
 * Check if a given object implements the PokemonType interface.
 */
export function instanceOfPokemonType(value: object): value is PokemonType {
    if (!('slot' in value) || value['slot'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function PokemonTypeFromJSON(json: any): PokemonType {
    return PokemonTypeFromJSONTyped(json, false);
}

export function PokemonTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PokemonType {
    if (json == null) {
        return json;
    }
    return {
        
        'slot': json['slot'],
        'type': NamedAPIResourceFromJSON(json['type']),
    };
}

export function PokemonTypeToJSON(json: any): PokemonType {
    return PokemonTypeToJSONTyped(json, false);
}

export function PokemonTypeToJSONTyped(value?: PokemonType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slot': value['slot'],
        'type': NamedAPIResourceToJSON(value['type']),
    };
}

