/* tslint:disable */
/* eslint-disable */
/**
 * @org/source
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NamedAPIResource } from './NamedAPIResource';
import {
    NamedAPIResourceFromJSON,
    NamedAPIResourceFromJSONTyped,
    NamedAPIResourceToJSON,
    NamedAPIResourceToJSONTyped,
} from './NamedAPIResource';

/**
 * Base stat values for the given Pokémon
 * @export
 * @interface PokemonStat
 */
export interface PokemonStat {
    /**
     * 
     * @type {NamedAPIResource}
     * @memberof PokemonStat
     */
    stat: NamedAPIResource;
    /**
     * The effort points (EV) the Pokémon has in the stat
     * @type {number}
     * @memberof PokemonStat
     */
    effort: number;
    /**
     * The base value of the stat
     * @type {number}
     * @memberof PokemonStat
     */
    base_stat: number;
}

/**
 * Check if a given object implements the PokemonStat interface.
 */
export function instanceOfPokemonStat(value: object): value is PokemonStat {
    if (!('stat' in value) || value['stat'] === undefined) return false;
    if (!('effort' in value) || value['effort'] === undefined) return false;
    if (!('base_stat' in value) || value['base_stat'] === undefined) return false;
    return true;
}

export function PokemonStatFromJSON(json: any): PokemonStat {
    return PokemonStatFromJSONTyped(json, false);
}

export function PokemonStatFromJSONTyped(json: any, ignoreDiscriminator: boolean): PokemonStat {
    if (json == null) {
        return json;
    }
    return {
        
        'stat': NamedAPIResourceFromJSON(json['stat']),
        'effort': json['effort'],
        'base_stat': json['base_stat'],
    };
}

export function PokemonStatToJSON(json: any): PokemonStat {
    return PokemonStatToJSONTyped(json, false);
}

export function PokemonStatToJSONTyped(value?: PokemonStat | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stat': NamedAPIResourceToJSON(value['stat']),
        'effort': value['effort'],
        'base_stat': value['base_stat'],
    };
}

