/* tslint:disable */
/* eslint-disable */
/**
 * @org/source
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OtherPokemonSprites } from './OtherPokemonSprites';
import {
    OtherPokemonSpritesFromJSON,
    OtherPokemonSpritesFromJSONTyped,
    OtherPokemonSpritesToJSON,
    OtherPokemonSpritesToJSONTyped,
} from './OtherPokemonSprites';
import type { VersionSprites } from './VersionSprites';
import {
    VersionSpritesFromJSON,
    VersionSpritesFromJSONTyped,
    VersionSpritesToJSON,
    VersionSpritesToJSONTyped,
} from './VersionSprites';

/**
 * A set of sprites used to depict this Pokémon in the game.
 * A visual representation of the various sprites can be found at [PokeAPI/sprites](https://github.com/PokeAPI/sprites#sprites)
 * @export
 * @interface PokemonSprites
 */
export interface PokemonSprites {
    /**
     * The default depiction of this Pokémon from the front in battle
     * @type {string}
     * @memberof PokemonSprites
     */
    front_default: string | null;
    /**
     * The shiny depiction of this Pokémon from the front in battle
     * @type {string}
     * @memberof PokemonSprites
     */
    front_shiny: string | null;
    /**
     * The female depiction of this Pokémon from the front in battle
     * @type {string}
     * @memberof PokemonSprites
     */
    front_female: string | null;
    /**
     * The shiny female depiction of this Pokémon from the front in battle
     * @type {string}
     * @memberof PokemonSprites
     */
    front_shiny_female: string | null;
    /**
     * The default depiction of this Pokémon from the back in battle
     * @type {string}
     * @memberof PokemonSprites
     */
    back_default: string | null;
    /**
     * The shiny depiction of this Pokémon from the back in battle
     * @type {string}
     * @memberof PokemonSprites
     */
    back_shiny: string | null;
    /**
     * The female depiction of this Pokémon from the back in battle
     * @type {string}
     * @memberof PokemonSprites
     */
    back_female: string | null;
    /**
     * The shiny female depiction of this Pokémon from the back in battle
     * @type {string}
     * @memberof PokemonSprites
     */
    back_shiny_female: string | null;
    /**
     * 
     * @type {OtherPokemonSprites}
     * @memberof PokemonSprites
     */
    other?: OtherPokemonSprites;
    /**
     * 
     * @type {VersionSprites}
     * @memberof PokemonSprites
     */
    versions: VersionSprites;
}

/**
 * Check if a given object implements the PokemonSprites interface.
 */
export function instanceOfPokemonSprites(value: object): value is PokemonSprites {
    if (!('front_default' in value) || value['front_default'] === undefined) return false;
    if (!('front_shiny' in value) || value['front_shiny'] === undefined) return false;
    if (!('front_female' in value) || value['front_female'] === undefined) return false;
    if (!('front_shiny_female' in value) || value['front_shiny_female'] === undefined) return false;
    if (!('back_default' in value) || value['back_default'] === undefined) return false;
    if (!('back_shiny' in value) || value['back_shiny'] === undefined) return false;
    if (!('back_female' in value) || value['back_female'] === undefined) return false;
    if (!('back_shiny_female' in value) || value['back_shiny_female'] === undefined) return false;
    if (!('versions' in value) || value['versions'] === undefined) return false;
    return true;
}

export function PokemonSpritesFromJSON(json: any): PokemonSprites {
    return PokemonSpritesFromJSONTyped(json, false);
}

export function PokemonSpritesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PokemonSprites {
    if (json == null) {
        return json;
    }
    return {
        
        'front_default': json['front_default'],
        'front_shiny': json['front_shiny'],
        'front_female': json['front_female'],
        'front_shiny_female': json['front_shiny_female'],
        'back_default': json['back_default'],
        'back_shiny': json['back_shiny'],
        'back_female': json['back_female'],
        'back_shiny_female': json['back_shiny_female'],
        'other': json['other'] == null ? undefined : OtherPokemonSpritesFromJSON(json['other']),
        'versions': VersionSpritesFromJSON(json['versions']),
    };
}

export function PokemonSpritesToJSON(json: any): PokemonSprites {
    return PokemonSpritesToJSONTyped(json, false);
}

export function PokemonSpritesToJSONTyped(value?: PokemonSprites | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'front_default': value['front_default'],
        'front_shiny': value['front_shiny'],
        'front_female': value['front_female'],
        'front_shiny_female': value['front_shiny_female'],
        'back_default': value['back_default'],
        'back_shiny': value['back_shiny'],
        'back_female': value['back_female'],
        'back_shiny_female': value['back_shiny_female'],
        'other': OtherPokemonSpritesToJSON(value['other']),
        'versions': VersionSpritesToJSON(value['versions']),
    };
}

