/* tslint:disable */
/* eslint-disable */
/**
 * @org/source
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Ruby/Sapphire sprites
 * @export
 * @interface RubySapphire
 */
export interface RubySapphire {
    /**
     * The default depiction of this Pokémon from the back in battle
     * @type {string}
     * @memberof RubySapphire
     */
    back_default: string | null;
    /**
     * The shiny depiction of this Pokémon from the back in battle
     * @type {string}
     * @memberof RubySapphire
     */
    back_shiny: string | null;
    /**
     * The default depiction of this Pokémon from the front in battle
     * @type {string}
     * @memberof RubySapphire
     */
    front_default: string | null;
    /**
     * The shiny depiction of this Pokémon from the front in battle
     * @type {string}
     * @memberof RubySapphire
     */
    front_shiny: string | null;
}

/**
 * Check if a given object implements the RubySapphire interface.
 */
export function instanceOfRubySapphire(value: object): value is RubySapphire {
    if (!('back_default' in value) || value['back_default'] === undefined) return false;
    if (!('back_shiny' in value) || value['back_shiny'] === undefined) return false;
    if (!('front_default' in value) || value['front_default'] === undefined) return false;
    if (!('front_shiny' in value) || value['front_shiny'] === undefined) return false;
    return true;
}

export function RubySapphireFromJSON(json: any): RubySapphire {
    return RubySapphireFromJSONTyped(json, false);
}

export function RubySapphireFromJSONTyped(json: any, ignoreDiscriminator: boolean): RubySapphire {
    if (json == null) {
        return json;
    }
    return {
        
        'back_default': json['back_default'],
        'back_shiny': json['back_shiny'],
        'front_default': json['front_default'],
        'front_shiny': json['front_shiny'],
    };
}

export function RubySapphireToJSON(json: any): RubySapphire {
    return RubySapphireToJSONTyped(json, false);
}

export function RubySapphireToJSONTyped(value?: RubySapphire | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'back_default': value['back_default'],
        'back_shiny': value['back_shiny'],
        'front_default': value['front_default'],
        'front_shiny': value['front_shiny'],
    };
}

