/* tslint:disable */
/* eslint-disable */
/**
 * @org/source
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GenerationVIISprites } from './GenerationVIISprites';
import {
    GenerationVIISpritesFromJSON,
    GenerationVIISpritesFromJSONTyped,
    GenerationVIISpritesToJSON,
    GenerationVIISpritesToJSONTyped,
} from './GenerationVIISprites';
import type { GenerationISprites } from './GenerationISprites';
import {
    GenerationISpritesFromJSON,
    GenerationISpritesFromJSONTyped,
    GenerationISpritesToJSON,
    GenerationISpritesToJSONTyped,
} from './GenerationISprites';
import type { GenerationVIIISprites } from './GenerationVIIISprites';
import {
    GenerationVIIISpritesFromJSON,
    GenerationVIIISpritesFromJSONTyped,
    GenerationVIIISpritesToJSON,
    GenerationVIIISpritesToJSONTyped,
} from './GenerationVIIISprites';
import type { GenerationIISprites } from './GenerationIISprites';
import {
    GenerationIISpritesFromJSON,
    GenerationIISpritesFromJSONTyped,
    GenerationIISpritesToJSON,
    GenerationIISpritesToJSONTyped,
} from './GenerationIISprites';
import type { GenerationIVSprites } from './GenerationIVSprites';
import {
    GenerationIVSpritesFromJSON,
    GenerationIVSpritesFromJSONTyped,
    GenerationIVSpritesToJSON,
    GenerationIVSpritesToJSONTyped,
} from './GenerationIVSprites';
import type { GenerationVISprites } from './GenerationVISprites';
import {
    GenerationVISpritesFromJSON,
    GenerationVISpritesFromJSONTyped,
    GenerationVISpritesToJSON,
    GenerationVISpritesToJSONTyped,
} from './GenerationVISprites';
import type { GenerationIIISprites } from './GenerationIIISprites';
import {
    GenerationIIISpritesFromJSON,
    GenerationIIISpritesFromJSONTyped,
    GenerationIIISpritesToJSON,
    GenerationIIISpritesToJSONTyped,
} from './GenerationIIISprites';
import type { GenerationVSprites } from './GenerationVSprites';
import {
    GenerationVSpritesFromJSON,
    GenerationVSpritesFromJSONTyped,
    GenerationVSpritesToJSON,
    GenerationVSpritesToJSONTyped,
} from './GenerationVSprites';

/**
 * Version Sprites
 * @export
 * @interface VersionSprites
 */
export interface VersionSprites {
    /**
     * 
     * @type {GenerationISprites}
     * @memberof VersionSprites
     */
    generation_i: GenerationISprites;
    /**
     * 
     * @type {GenerationIISprites}
     * @memberof VersionSprites
     */
    generation_ii: GenerationIISprites;
    /**
     * 
     * @type {GenerationIIISprites}
     * @memberof VersionSprites
     */
    generation_iii: GenerationIIISprites;
    /**
     * 
     * @type {GenerationIVSprites}
     * @memberof VersionSprites
     */
    generation_iv: GenerationIVSprites;
    /**
     * 
     * @type {GenerationVSprites}
     * @memberof VersionSprites
     */
    generation_v: GenerationVSprites;
    /**
     * 
     * @type {GenerationVISprites}
     * @memberof VersionSprites
     */
    generation_vi: GenerationVISprites;
    /**
     * 
     * @type {GenerationVIISprites}
     * @memberof VersionSprites
     */
    generation_vii: GenerationVIISprites;
    /**
     * 
     * @type {GenerationVIIISprites}
     * @memberof VersionSprites
     */
    generation_viii: GenerationVIIISprites;
}

/**
 * Check if a given object implements the VersionSprites interface.
 */
export function instanceOfVersionSprites(value: object): value is VersionSprites {
    if (!('generation_i' in value) || value['generation_i'] === undefined) return false;
    if (!('generation_ii' in value) || value['generation_ii'] === undefined) return false;
    if (!('generation_iii' in value) || value['generation_iii'] === undefined) return false;
    if (!('generation_iv' in value) || value['generation_iv'] === undefined) return false;
    if (!('generation_v' in value) || value['generation_v'] === undefined) return false;
    if (!('generation_vi' in value) || value['generation_vi'] === undefined) return false;
    if (!('generation_vii' in value) || value['generation_vii'] === undefined) return false;
    if (!('generation_viii' in value) || value['generation_viii'] === undefined) return false;
    return true;
}

export function VersionSpritesFromJSON(json: any): VersionSprites {
    return VersionSpritesFromJSONTyped(json, false);
}

export function VersionSpritesFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionSprites {
    if (json == null) {
        return json;
    }
    return {
        
        'generation_i': GenerationISpritesFromJSON(json['generation-i']),
        'generation_ii': GenerationIISpritesFromJSON(json['generation-ii']),
        'generation_iii': GenerationIIISpritesFromJSON(json['generation-iii']),
        'generation_iv': GenerationIVSpritesFromJSON(json['generation-iv']),
        'generation_v': GenerationVSpritesFromJSON(json['generation-v']),
        'generation_vi': GenerationVISpritesFromJSON(json['generation-vi']),
        'generation_vii': GenerationVIISpritesFromJSON(json['generation-vii']),
        'generation_viii': GenerationVIIISpritesFromJSON(json['generation-viii']),
    };
}

export function VersionSpritesToJSON(json: any): VersionSprites {
    return VersionSpritesToJSONTyped(json, false);
}

export function VersionSpritesToJSONTyped(value?: VersionSprites | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'generation-i': GenerationISpritesToJSON(value['generation_i']),
        'generation-ii': GenerationIISpritesToJSON(value['generation_ii']),
        'generation-iii': GenerationIIISpritesToJSON(value['generation_iii']),
        'generation-iv': GenerationIVSpritesToJSON(value['generation_iv']),
        'generation-v': GenerationVSpritesToJSON(value['generation_v']),
        'generation-vi': GenerationVISpritesToJSON(value['generation_vi']),
        'generation-vii': GenerationVIISpritesToJSON(value['generation_vii']),
        'generation-viii': GenerationVIIISpritesToJSON(value['generation_viii']),
    };
}

