/* tslint:disable */
/* eslint-disable */
/**
 * @org/source
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PokemonDetails,
} from '../models/index';
import {
    PokemonDetailsFromJSON,
    PokemonDetailsToJSON,
} from '../models/index';

export interface GetPokemonRequest {
    versionGroupId: number;
}

/**
 * 
 */
export class PokemonApi extends runtime.BaseAPI {

    /**
     */
    async getPokemonRaw(requestParameters: GetPokemonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PokemonDetails>>> {
        if (requestParameters['versionGroupId'] == null) {
            throw new runtime.RequiredError(
                'versionGroupId',
                'Required parameter "versionGroupId" was null or undefined when calling getPokemon().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['versionGroupId'] != null) {
            queryParameters['versionGroupId'] = requestParameters['versionGroupId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/pokemon`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PokemonDetailsFromJSON));
    }

    /**
     */
    async getPokemon(requestParameters: GetPokemonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PokemonDetails>> {
        const response = await this.getPokemonRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
